CONFIGURATION:
  data_path: ../../datasets/dynamics/SD1/data_parquet/
  data_type: petastorm
  epochs: 200
  feature: signal
  loss: categorical_crossentropy
  target: target
MANIPULATION:
  channel_first: 'false'
  feature_scaling: standard
  resizing_len:
  - quantile
  - 0.95
  resizing_method: end
  target_encoding: one_hot_encoder
MODEL:
  act_fn_name: relu
  batch_size: 128
  cell_array:
  - 128
  - 128
  - 128
  dropout: 0.2
  model_type: bilstm
