CONFIGURATION:
  data_path: ../../datasets/dynamics/SD1/data_parquet/
  data_type: petastorm
  epochs: 200
  feature: signal
  loss: categorical_crossentropy
  target: target
MANIPULATION:
  channel_first: 'false'
  feature_scaling: standard
  resizing_len:
  - quantile
  - 0.95
  resizing_method: end
  target_encoding: one_hot_encoder
MODEL:
  act_fn_name: relu
  batch_size: 128
  dropout: 0.3
  input_dropout: 0.2
  mlp_dim: 128
  model_dim: 128
  model_type: transformer
  num_heads: 8
  num_layers: 4
